### ISSUE TITLE
from Hung about your project 1

### ISSUE THREAD

**Issue by hungmuha** [RettBehrens/project-1#2]
Your javascript is readable but I think you can do a little more organizing by getting the variable to be all declared earlier. 

you can set your game to be screen responsive.

you can get the game to work correctly as one instant that the player 1 was suppose to win but didn't so I think your winning condition can be fixed and maybe the reset condition also.

**Comment by RettBehrens** [comment]
i think I fixed the functionality issues. In an attempt to make the CSS responsive, I created new styling issues...
