### ISSUE TITLE
Functionality Issue

### ISSUE THREAD

**Issue by enderwillsaveu** [RettBehrens/project-1#3]
Upon playing and finishing your game I got the correct win statement. I hit the reset button which reset the scripts - indicating that it was Player Ones turn. However the score was added to player two (the scores were showing 0-0 but it didn't seem to actually clear the score. Maybe just running the debugger over the score keeping functions to straighten that out

**Comment by RettBehrens** [comment]
fixed.. I think. Just not on gh-pages yet
